name: Build and Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build for Android ARM64
      run: |
        GOOS=android GOARCH=arm64 go build -o timecron main.go

    - name: Archive build
      run: |
        tar -czvf timecron-android-arm64-${{ github.event.inputs.version }}.tar.gz timecron

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ github.event.inputs.version }}
        files: |
          timecron-android-arm64-${{ github.event.inputs.version }}.tar.gz
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
